exports.BattlePokedex = {
butterfree:{num:12,species:"Butterfree",types:["Bug","Flying"],baseStats:{hp:105,atk:60,def:88,spa:85,spd:105,spe:82},abilities:{0:"Compoundeyes",1:"Swarm",DW:"Tinted Lens"},heightm:1.1,weightkg:32,color:"White",prevo:"metapod",evoLevel:10,eggGroups:["Bug"]},
beedrill:{num:15,species:"Beedrill",types:["Bug","Poison"],baseStats:{hp:85,atk:108,def:55,spa:95,spd:75,spe:107},abilities:{0:"Swarm",1:"Technician",DW:"Sniper"},heightm:1,weightkg:29.5,color:"Yellow",prevo:"kakuna",evoLevel:10,eggGroups:["Bug"]},
pikachu:{num:25,species:"Pikachu",types:["Electric"],baseStats:{hp:75,atk:70,def:55,spa:75,spd:70,spe:105},abilities:{0:"Static",DW:"Lightningrod"},heightm:0.4,weightkg:6,color:"Yellow",prevo:"pichu",evos:["raichu"],evoLevel:1,eggGroups:["Ground","Fairy"]},
vulpix:{num:37,species:"Vulpix",types:["Fire"],genderRatio:{M:0.25,F:0.75},baseStats:{hp:85,atk:65,def:70,spa:85,spd:100,spe:65},abilities:{0:"Magic Guard",DW:"Drought"},heightm:0.6,weightkg:9.9,color:"Brown",evos:["ninetales"],eggGroups:["Ground"]},
poliwhirl:{num:61,species:"Poliwhirl",types:["Water"],baseStats:{hp:70,atk:80,def:70,spa:85,spd:70,spe:105},abilities:{0:"Water Absorb",1:"Drizzle",DW:"Swift Swim"},heightm:1,weightkg:20,color:"Blue",prevo:"poliwag",evos:["poliwrath","politoed"],evoLevel:25,eggGroups:["Water 1"]},
machoke:{num:67,species:"Machoke",types:["Fighting"],genderRatio:{M:0.75,F:0.25},baseStats:{hp:95,atk:125,def:85,spa:40,spd:80,spe:55},abilities:{0:"Guts",1:"No Guard",DW:"Big Pecks"},heightm:1.5,weightkg:70.5,color:"Gray",prevo:"machop",evos:["machamp"],evoLevel:28,eggGroups:["Humanshape"]},
marowak:{num:105,species:"Marowak",types:["Ground"],baseStats:{hp:100,atk:105,def:105,spa:65,spd:75,spe:50},abilities:{0:"Rock Head",1:"Lightningrod",DW:"Battle Armor"},heightm:1,weightkg:45,color:"Brown",prevo:"cubone",evoLevel:28,eggGroups:["Monster"]},
ninjask:{num:291,species:"Ninjask",types:["Bug","Flying"],baseStats:{hp:70,atk:90,def:50,spa:50,spd:60,spe:180},abilities:{0:"Speed Boost",DW:"Infiltrator"},heightm:0.8,weightkg:12,color:"Yellow",prevo:"nincada",evoLevel:20,eggGroups:["Bug"]},
tropius:{num:357,species:"Tropius",types:["Grass","Flying"],baseStats:{hp:105,atk:85,def:85,spa:110,spd:110,spe:45},abilities:{0:"Chlorophyll",1:"Solar Power",DW:"Harvest"},heightm:2,weightkg:100,color:"Green",eggGroups:["Monster","Plant"]},
rampardos:{num:409,species:"Rampardos",types:["Rock"],genderRatio:{M:0.875,F:0.125},baseStats:{hp:82,atk:165,def:60,spa:95,spd:60,spe:78},abilities:{0:"Mold Breaker",DW:"Sheer Force"},heightm:1.6,weightkg:102.5,color:"Blue",prevo:"cranidos",evoLevel:30,eggGroups:["Monster"]},
hippopotas:{num:449,species:"Hippopotas",types:["Ground"],baseStats:{hp:110,atk:100,def:100,spa:55,spd:60,spe:55},abilities:{0:"Sand Stream",DW:"Sand Force"},heightm:0.8,weightkg:49.5,color:"Brown",evos:["hippowdon"],eggGroups:["Ground"]},
snover:{num:459,species:"Snover",types:["Grass","Ice"],baseStats:{hp:90,atk:80,def:85,spa:80,spd:95,spe:50},abilities:{0:"Snow Warning",DW:"Soundproof"},heightm:1,weightkg:50.5,color:"White",evos:["abomasnow"],eggGroups:["Monster","Plant"]},
regigigas:{num:486,species:"Regigigas",types:["Normal"],gender:"N",baseStats:{hp:130,atk:160,def:130,spa:50,spd:130,spe:100},abilities:{0:"Slow Start"},heightm:3.7,weightkg:420,color:"White",eggGroups:["No Eggs"]},
serperior:{num:497,species:"Serperior",types:["Grass","Dragon"],genderRatio:{M:0.875,F:0.125},baseStats:{hp:92,atk:75,def:95,spa:75,spd:95,spe:108},abilities:{0:"Overgrow",DW:"Solar Power"},heightm:3.3,weightkg:63,color:"Green",prevo:"servine",evoLevel:36,eggGroups:["Ground","Plant"]},
gurdurr:{num:533,species:"Gurdurr",types:["Fighting"],genderRatio:{M:0.75,F:0.25},baseStats:{hp:105,atk:110,def:105,spa:55,spd:65,spe:40},abilities:{0:"Guts",1:"Sheer Force",DW:"Iron Fist"},heightm:1.2,weightkg:40,color:"Gray",prevo:"timburr",evos:["conkeldurr"],evoLevel:25,eggGroups:["Humanshape"]},
seismitoad:{num:537,species:"Seismitoad",types:["Water","Ground"],baseStats:{hp:105,atk:90,def:80,spa:90,spd:80,spe:85},abilities:{0:"Swift Swim",1:"Poison Heal",DW:"Water Absorb"},heightm:1.5,weightkg:62,color:"Blue",prevo:"palpitoad",evoLevel:36,eggGroups:["Water 1"]},
duosion:{num:578,species:"Duosion",types:["Psychic"],baseStats:{hp:85,atk:60,def:70,spa:125,spd:80,spe:30},abilities:{0:"Overcoat",1:"Magic Guard",DW:"Regenerator"},heightm:0.6,weightkg:8,color:"Green",prevo:"solosis",evos:["reuniclus"],evoLevel:32,eggGroups:["Indeterminate"]},
fraxure:{num:611,species:"Fraxure",types:["Dragon"],baseStats:{hp:90,atk:127,def:85,spa:55,spd:60,spe:83},abilities:{0:"Rivalry",1:"Mold Breaker",DW:"Sheer Force"},heightm:1,weightkg:36,color:"Green",prevo:"axew",evos:["haxorus"],evoLevel:38,eggGroups:["Monster","Dragon"]},
shelmet:{num:616,species:"Shelmet",types:["Bug"],baseStats:{hp:70,atk:40,def:105,spa:85,spd:105,spe:45},abilities:{0:"Hydration",1:"Shell Armor",DW:"Dry Skin"},heightm:0.4,weightkg:7.7,color:"Red",evos:["accelgor"],eggGroups:["Bug"]},
golurk:{num:623,species:"Golurk",types:["Ground","Ghost"],gender:"N",baseStats:{hp:105,atk:120,def:90,spa:60,spd:90,spe:65},abilities:{0:"Iron Fist",1:"Solid Rock",DW:"No Guard"},heightm:2.8,weightkg:330,color:"Green",prevo:"golett",evoLevel:43,eggGroups:["Mineral"]},
zweilous:{num:634,species:"Zweilous",types:["Dark","Dragon"],baseStats:{hp:90,atk:108,def:90,spa:65,spd:90,spe:82},abilities:{0:"Hustle",1:"Rivalry"},heightm:1.4,weightkg:50,color:"Blue",prevo:"deino",evos:["hydreigon"],evoLevel:50,eggGroups:["Dragon"]}
};

